vich_uploader:
    db_driver: orm

    mappings:
        performer:
            uri_prefix: /img/performer
            upload_destination: '%kernel.project_dir%/public/img/performer'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        act:
            uri_prefix: /img/act
            upload_destination: '%kernel.project_dir%/public/img/act'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
